# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
  push:
    branches: [main]

env:
  IMAGE: ghcr.io/${{ github.repository }}

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26"
          cache: true
      - name: Run tests
        run: go test ./...
      - name: Run concurrency tests
        run: go test -race ./...

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26"
      - name: GoSec
        uses: securego/gosec@master
        with:
          args: ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
